name: course-evaluation
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependecies
        run: npm ci
      - name: Lint Fix All Files
        run: npm run lint:fix -- .

  evaluation:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependecies
        run: npm ci
      - name: Evaluation Project
        run: TIMEOUT_VALIDATION=0 #npm run evaluate

  integration:
    needs:
      - lint
      - evaluation
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v3
      - name: Auto Merge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
