name: course-evaluation
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:

  update_branch:
    name: Update branch with master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Updating branch with master
        run: |
          git checkout ${{ github.head_ref }} --
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.head_ref }}"
          git pull origin master
          git push origin ${{ github.head_ref }}

  notify_opened:
    needs:
      - update_branch
    name: Notify new change
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_PERSONAL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <strong>ℹ️ Pull Request on ${{ github.event.action }} pending!</strong>

            ${{ github.actor }} - from ${{ github.head_ref }}

  lint:
    needs:
      - notify_opened
    name: Clean all repository code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependecies
        run: npm install
      - name: Lint Fix All Files
        run: |
          npm run lint:fix -- . --rule 'import/no-unresolved: off'
        
  evaluation:
    needs:
      - lint
    name: Do evaluation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependecies
        run: npm install
      - name: Evaluation Project
        run: DB_URI="${{ secrets.DB_URI }}" TIMEOUT_VALIDATION=5 DEBUG_SERVER=true TIMEOUT_VALIDATION=0 npm run evaluate

  notify_approved:
    needs:
      - evaluation
    name: Notify Approved to Teacher
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on pull request approved
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_PERSONAL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <strong>✅ Pull Request on ${{ github.event.action }} approved!</strong>

            ${{ github.actor }} - from ${{ github.head_ref }}
  email:
    needs:
      - evaluation
    name: Notify Approved to Student
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependecies
        run: npm install
      - name: Send Email
        run: GMAIL_USERNAME='${{ secrets.GMAIL_USERNAME }}' GMAIL_PASSWORD='${{ secrets.GMAIL_PASSWORD }}' STUDENTS='${{ secrets.STUDENTS }}' npm run send:mail ${{ github.head_ref }}
