name: course-evaluation
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependecies
        run: npm install
      - name: Lint
        run: npm run lint:fix -- .

  evaluation:
    needs: [lint]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Dependecies
        run: npm install
      - name: Evaluation
        run: npm run evaluate

  integration:
    needs: [lint, evaluation]
    runs-on: ubuntu-20.04
    steps:
      - name: Merge with master
      - run: |
          echo "Merge with master"
